# Generated by Django 3.0.6 on 2020-06-12 14:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=35)),
                ('address1', models.CharField(blank=True, default='', max_length=55)),
                ('address2', models.CharField(blank=True, default='', max_length=55)),
                ('city', models.CharField(blank=True, default='', max_length=35)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=140)),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=165)),
            ],
            options={
                'verbose_name': 'Objective',
                'verbose_name_plural': 'Objectives',
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=180)),
                ('indomain', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects_app.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposaldate', models.DateField(default=datetime.datetime.now, verbose_name='Proposal Date')),
                ('startdate', models.DateField(default=datetime.datetime.now, verbose_name='Start Date')),
                ('enddate', models.DateField(default=datetime.datetime.now, verbose_name='End Date')),
                ('fees', models.IntegerField(default=0)),
                ('feesaftergrant', models.IntegerField(default=0, verbose_name='Fees after grant')),
                ('billing1', models.CharField(default='30% upon appointment of our services', max_length=50, verbose_name='First Billing')),
                ('billing2', models.CharField(default='60% upon issuance of draft report', max_length=50, verbose_name='Second Billing')),
                ('billing3', models.CharField(default='10% upon issuance of follow up report', max_length=50, verbose_name='Final Billing')),
                ('proptemplate', models.CharField(default='sample.pptx', max_length=50)),
                ('engatemplate', models.CharField(default='sample.docx', max_length=50)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects_app.Customer')),
                ('domains', models.ManyToManyField(blank=True, to='projects_app.Domain')),
                ('objectives', models.ManyToManyField(blank=True, to='projects_app.Objective')),
                ('workitems', models.ManyToManyField(blank=True, to='projects_app.WorkItem')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(help_text='Enter description of document', max_length=300)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='document')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_app.Project')),
                ('workitem_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_app.WorkItem')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
