# Generated by Django 3.0.5 on 2020-06-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0002_auto_20200609_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('IP', 'In progress'), ('ENDED', 'Ended')], default='INITIATED', max_length=20),
        ),
    ]
