# Generated by Django 3.0.5 on 2020-06-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0003_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('IP', 'In progress'), ('ENDED', 'Ended')], default='Initiated', max_length=20),
        ),
    ]
