# Generated by Django 3.0.5 on 2020-06-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0005_project_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('IN_PROGRESS', 'In progress'), ('ENDED', 'Ended')], default='Initiated', max_length=20),
        ),
    ]
