# Generated by Django 3.0.5 on 2020-06-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0006_auto_20200618_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address1',
            field=models.CharField(blank=True, default='', max_length=55, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=55, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, default='', max_length=35, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, default='', max_length=35, verbose_name='Customer name'),
        ),
    ]
