# Generated by Django 3.0.7 on 2020-07-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0008_auto_20200626_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columndata', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
